cc_library(
    name = "tadiran_ac_blynk",
    srcs = ["main.cc"],
    copts = ["-Iexternal/blynk/src", "-Iexternal/blynk/linux"],
    deps = ["@blynk//:blynk-lib"],
    visibility = ["//visibility:public"],
)
